language: node_js
node_js:
  - stable
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
install:
  - npm ci
script:
  - npm run build
  - npm run typedoc
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run coveralls
    on:
      branch: main
      # only on untagged versions.
      tags: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    on:
      branch: main
      # only on untagged versions.
      tags: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  - provider: npm
    skip_cleanup: true
    tag: prerelease
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    on:
      branch: main
      # only on tagged versions.
      tags: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[^[:space:]]+$
  - provider: pages
    skip_cleanup: true
    keep_history: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    on:
      branch: main
      # only on untagged versions.
      tags: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
