name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [current]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Restore
        run: npm ci

      - name: Test
        run: npm test

      - name: Docs
        run: npm run docs

      - name: Publish (NPM)
        continue-on-error: true
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish (GitHub Pages)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.

      - name: Publish (CodeCov)
        uses: codecov/codecov-action@v3
        with:
          files: ./out/coverage/lcov.info
          fail_ci_if_error: true
          verbose: true
